# Generated by Django 5.1.3 on 2024-12-06 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
