# Generated by Django 5.1.3 on 2024-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_qr_code_image_user_qr_code_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_code_image',
        ),
        migrations.AddField(
            model_name='user',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
