# Generated by Django 5.1.3 on 2025-06-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_project_deadline'),
        ('Team', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('progress_notes', models.TextField(blank=True)),
                ('frontend_percent', models.IntegerField(default=0)),
                ('backend_percent', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Client.project')),
            ],
        ),
    ]
