# Generated by Django 5.1.3 on 2025-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_projectprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
