# Generated by Django 5.1.3 on 2024-12-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_task_assigner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='deadline',
        ),
    ]
