# Generated by Django 5.1.3 on 2025-02-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_rename_end_date_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigner', to='Team.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Team.employee'),
        ),
    ]
