# Generated by Django 5.1.3 on 2025-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_alter_task_assigner_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee/default.webp', null=True, upload_to='employee'),
        ),
    ]
