# Generated by Django 5.1.3 on 2025-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'EMPLOYEE'), ('manager', 'MANAGER')], default='employee', max_length=20),
        ),
    ]
